### ISSUE TITLE
No matching distribution found for pythonocc-core when using pip install

### ISSUE THREAD

**Issue by ldgarcia** [tpaviot/pythonocc-core#106]
I tried installing pythonocc-core with `pip`, but an error occurs:

````bash
$ pip search pythonocc
pythonocc-core     - pythonocc-core wraps the OpenCASCADE CAD Kernel
$ pip install pythonocc-core
Collecting pythonocc-core
  Could not find a version that satisfies the requirement pythonocc-core (from versions: )
No matching distribution found for pythonocc-core
````

I will use `conda` instead, but I decided to open this since pythonocc-core is still listed in PyPI.

**Comment by jf---** [comment]
good point @ldgarcia ...
I think its important that pythonocc is present in PyPI since its such an authorative reference for the python eco system. However, the right approach would be that trying to install by pip would result in getting a link to instructions explaining you what your options are on the specific platform...

thanks again,

-jelle

**Comment by ldgarcia** [comment]
Yes, that would be a very good approach @jf---

**Comment by tpaviot** [comment]
pip support is not planned.
