### ISSUE TITLE
Substitute of BRepTools.breptools_WriteToString?

### ISSUE THREAD

**Issue by romanavyzn** [tpaviot/pythonocc-core#1330]
With pythonocc "7.6.2" I used `BRepTools.breptools_WriteToString(shape)` and `BRepTools.breptools_ReadFromString(str)` to serialize and deserialize a `TopoDS_Shape`.
With upgrading to 7.7.2 these functions do not exist anymore.
Which methods do I have to use now to convert a shape into a string?
Thanks in advance.

**Comment by tpaviot** [comment]
in older pythonocc releases, static functions used to be wrapped as `classname_staticfunctionname`, since SWIG release 4.1, it is `classname.staticfunctioname`. You should be able to continue using `breptools_WriteToString(shape)`  with a deprecation warning being raised, it's not the case? FYI version 7.8.1 is about to be released in the coming hours/days, without any API change regarding this topic
