### ISSUE TITLE
port algodia examples

### ISSUE THREAD

**Issue by jf---** [tpaviot/pythonocc-core#325]
[see here](http://www.algotopia.com/contents/opencascade/opencascade_sprocket)

**Comment by chentao807** [comment]
as you wish, @jf--- 
https://gist.github.com/chentao807/b1774deed8eacf009c8492947d283a04

Just work, but no best.  Make anything better if you can

**Comment by jf---** [comment]
nice work @chentao807.... thanks 💐 

so I could copy the snippet, but probably best is if you make a pull request, this way you'll show up as a contributor to the project... 

we wouldnt want to steal the hard earned karma ;)

awesome, code looks mint if you ask me 🏆

**Comment by jf---** [comment]
Awesome @chentao807 

![image](https://cloud.githubusercontent.com/assets/620988/18885022/347da01a-84ea-11e6-8cb6-6d5b42b7dfca.png)

**Comment by tpaviot** [comment]
This is quite an amount of work, well done @chentao807 Please open a PR so that this is included in our example suite. 2 modifications reqsuested:

* add a license header (see the files in the /examples directory) with your name/email

* we use underscores to name functions. You should move all your functions names to underscores (buildTooth->build_tooth etc.)

**Comment by rainman110** [comment]
@chentao807 Wow, great work! :tada:  I also modelled gears ones and I know how much work this can be :smirk:

**Comment by tpaviot** [comment]
There is one more example to port see http://www.algotopia.com/contents/opencascade/opencascade_basic

**Comment by jf---** [comment]
@tpaviot OK on it...
