### ISSUE TITLE
Identify common upstream OCC bugs for pythonocc and FreeCAD

### ISSUE THREAD

**Issue by luzpaz** [tpaviot/pythonocc-core#423]
Greetings, I hang out over at FreeCAD. I'm not a dev but just a volunteer so I'm not representing the FreeCAD project officially. 

Gist: I have identified all current open upstream OCC bugs that affect FreeCAD. The link to that list is in https://forum.freecadweb.org/viewtopic.php?f=8&t=22385
The reason I've opened this ticket is to initiate a potential collaboration with other CAD programs that use OCC in order to consolidate resources and help get these upstream bugs expedited. Thanks for your time. Any feedback is appreciated.

**Comment by tpaviot** [comment]
@luzpaz pythonocc is not sync'ed with latest occt release. It is based upon oce, which is always behind occt. As a consequence, pythonocc is not the best project to test and report occt bugs, since they might have already been reported/fixed and made available in lastest occt release.

If you identify what you suspect to be an occt bug, please report it to the mantis bugtracker.
