### ISSUE TITLE
Install does not respect CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by mmorandi** [tpaviot/pythonocc-core#598]
If one wants to install pythonocc into some non-standard location setting CMAKE_INSTALL_PREFIX  is of no use because the line

set(PYTHONOCC_INSTALL_DIRECTORY ${python_lib}/OCC CACHE PATH "pythonOCC install directory" )

in CMakeLists.txt is executed:

[100%] Built target _ShapeProcessAPI
Install the project...
-- Install configuration: "MinSizeRel"
CMake Error at cmake_install.cmake:49 (file):
  file cannot create directory: /usr/lib/python3.6/site-packages/OCC.  Maybe
  need administrative privileges.

with

marco@pao:~/Projects/Chierichetti/src_SONATA/pythonocc-core-0.18.1/build> grep CMAKE_INSTALL_PREFIX CMakeCache.txt 
CMAKE_INSTALL_PREFIX:PATH=/home/marco/local/Fenics

**Comment by rabbidous** [comment]
I would like to add to more reason to respect CMAKE_INSTALL_PREFIX (and up-vote this issue).

I am trying to build development versions of OCE and PythonOCC link them together and install them into a non-standard location (together). I made a simple CMAKE "superbuild" script out-of-directory build to compile OCE and then compile PythonOCC using the newly built OCE.

Since neither project respects CMAKE_INSTALL_PREFIX, the build is unpredictable and keeps reverting to system install locations. I've spent way to much time trying to get one project to find the other without installing (development) versions in a system location which shouldn't be necessary.

Maybe there is a more sanctioned method to do this, but I haven't figured it out yet.
