### ISSUE TITLE
DLL Load Error on Windows

### ISSUE THREAD

**Issue by servo270** [tpaviot/pythonocc-core#790]
I have been trying to get pythonocc to work recently, but have been running into the following error:
![grafik](https://user-images.githubusercontent.com/32885969/76615320-18f19380-6522-11ea-857d-6d27f323f091.png)

Sytem information: Windows 10 Pro Education
Python Version: installed up to 3.7, using 3.6 for environment
PythonOCC version: 7.4.0
Installed by: conda install -c dlr-sc pythonocc-core 
Relavent conda environment setup:
![grafik](https://user-images.githubusercontent.com/32885969/76617245-31fc4380-6526-11ea-8d86-7abacb05ce63.png)
System user path:
![grafik](https://user-images.githubusercontent.com/32885969/76615044-8650f480-6521-11ea-9bfc-798531a3c3c6.png)

To trigger the error, the following was run:
`from OCC.Visualization import Display3d`

**Comment by rainman110** [comment]
Hi @servo270! Could you please print also the output of ```conda list```.

**Comment by servo270** [comment]
@rainman110 attached is the output (it's too long to paste here)
[conda list.txt](https://github.com/tpaviot/pythonocc-core/files/4329280/conda.list.txt)

**Comment by rainman110** [comment]
Wow... these are a lot of packages. Hard to figure out, what the cause of the problem is.

I see, you are still using pythonocc 0.17.3 (not 7.4.0). This is okay, as TiGL does not yet support a newer version yet.


The first step I would do in your case is to create a clean conda environment:
conda create -n occtest python=3.6 pythonocc-core=0.17.3
conda activate occtest

Then try again import the Visualization package. If this works, try adding other packages one after another. This way, we could figure out, where the DLL collision comes from.

**Comment by servo270** [comment]
Unclear what caused the original collision problem, but manually reinstalling the packages starting with:
conda create -n envname python=3.6 pythonocc-core=0.17.3

eliminated the issue
