### ISSUE TITLE
Type hints and/or pathlib support for OCC.Extend.DataExchange

### ISSUE THREAD

**Issue by dmontagu** [tpaviot/pythonocc-core#884]
Really great to have all the mypy-friendly type hints throughout the library these days!

One stumbling block I still occasionally trip over is the lack of pathlib support in functions like `OCC.Extend.DataExchange.read_step_file` or `write_step_file`, which results in a somewhat cryptic error message:

```
File "/usr/local/lib/python3.8/site-packages/OCC/Extend/DataExchange.py", line 119, in write_step_file
  status = step_writer.Write(filename)
File "/usr/local/lib/python3.8/site-packages/OCC/Core/STEPControl.py", line 934, in Write
  return _STEPControl.STEPControl_Writer_Write(self, *args)
TypeError: in method 'STEPControl_Writer_Write', argument 2 of type 'char const *'
```

Adding support for pathlib would be nice (just call `str` on anything received as a filename), but more generally this could be addressed by just adding type hints to the file `OCC.Extend.DataExchange` that would remind me not to pass pathlib `Path` instances.

I am happy to add the type hints myself and open a PR, but I don't know what conventions you'd prefer they follow.

In particular, I'm not sure whether you'd prefer the use of a stubs file or inline annotations, if there are any formatting requirements, etc.

Let me know if this is something you're interested in.

**Comment by tpaviot** [comment]
@dmontagu I use stub files for main pythonocc modules that wrap c++ code (e.g. BRepPrimAPI, Geom2dGcc etc.) because SWIG cannot handle type hints natively. However, for pure python modules (all the modules located in the folder /Extend for example), type hints can be inserted as annotations. I guess I started to do it for some modules, but did not have time to complete the work. So feel free to contribute a PR that includes type annotations.
