### ISSUE TITLE
ShapeAnalysis_Curve static methods

### ISSUE THREAD

**Issue by aothms** [tpaviot/pythonocc-core#97]
Hi,

I am not entirely sure, maybe I got confused about static and member methods, but I cannot get OCC.ShapeAnalysis.ShapeAnalysis_Curve.Project() to work. Using 0.16.0.

From the signature I would be tempted to think it is a static method, but it doesn't seem to be, but there also isn't a constructor defined for ShapeAnalysis_Curve. Therefore both snippets do not seem to work:

    u = OCC.ShapeAnalysis.ShapeAnalysis_Curve.Project(curve_handle, pnt, prec, a, b)
    
    c = OCC.ShapeAnalysis.ShapeAnalysis_Curve()
    u = c.Project(curve_handle, pnt, prec, a, b)

OCC.GeomAPI.GeomAPI_ProjectPointOnCurve works fine and provides projection functionality as well, not an urgent issue.

Kind regards,
Thomas

**Comment by tpaviot** [comment]
@aothms Good catch. From the orginal oce header, Project is actually not a static function. A ShapeAnalaysis_Curve instance has first to be created before the Project method can be called. So the right way to use this function is (and you(re right):

    c = OCC.ShapeAnalysis.ShapeAnalysis_Curve()
    u = c.Project(curve_handle, pnt, prec, a, b)

There's an issue in the python wrapper: no constructor is defined, thus the first line raises an exception.

I agree with you that the user can be confused between static function and member functions. I will add something in the method docstring in order to help the user.
